---
fixtures:
  repositories:
    concat: https://github.com/puppetlabs/puppetlabs-concat
    epel: https://github.com/stahnma/puppet-module-epel.git
    python: https://github.com/stankevich/puppet-python
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib
    systemd: https://github.com/voxpupuli/puppet-systemd
    yumrepo_core: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
